server:
  ## TODO random port for development env. need to fix port in production env
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  cloud:
    bootstrap:
      enabled:
        true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      ## TODO need to be replaced with ip of eureka server loadbalancer
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

token:
  expiration_time: 86400000
  secret: 1234
